services:
  stats:
    image: virtualzone/docker-container-stats
    container_name: docker-stats
    hostname: docker-stats
    ports:
      - 8383:8080
    environment:
      STATS_UPDATE_INTERVAL: 10
    dns: 
      - <ipv4 dns>
      - <ipv6 dns>

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /portainer/Files/AppData/Config/docker-stats/db:/opt/docker-stats/db
