---
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    hostname: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Portugal/Lisbon 
      - SUBDOMAINS=<Subdomain_Name>
      - TOKEN=<duckdns_Token>
      - UPDATE_IP=both #optional
      - LOG_FILE=true #optional
    volumes:
      - /home/PI/dockerFiles/duckdns/config:/config #optional
    restart: unless-stopped
    dns: 
      - <ipv4 dns>
      - <ipv6 dns>
