services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/PI/dockerFiles/homeAssistant/config:/config
      - /home/PI/dockerFiles/homeAssistant/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GPIO ZERO_PIN_FACTORY=pigpio 
      - PIGPIO_ADDR=<GPIO_Addess>
    restart: unless-stopped
    hostname: "homeassistant.local"
    privileged: true
    network_mode: host
    dns: 
      - <ipv4 dns>
      - <ipv6 dns>



#docker run -d   --name homeassistant   --privileged   --restart=unless-stopped   -e TZ=MY_TIME_ZONE   -v /home/homeassistant/:/config   -v /run/dbus:/run/dbus:ro   --network=host   ghcr.io/home-assistant/home-assistant:stable
