services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Lisbon/Portugal
    volumes:
      - /home/PI/dockerFiles/jellyfin/jellyfin-config:/config
      - /home/PI/media:/media
      - /srv/dev-disk-by-uuid-...../Filmes:/media2
    ports:
      - 8096:8096
    restart: unless-stopped
    dns: 
      - <ipv4 dns>
      - <ipv6 dns>
volumes:
  jellyfin-config:
