version: '2'
services:
  db:
    image: yobasystems/alpine-mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    #restart: always
    volumes:
      - /home/priminas5/dockerFiles/nextcloud/nextclouddb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=8520
      - MYSQL_PASSWORD=8520
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    dns: 
      - 172.173.174.62
      - 2001:8a0:f2ff:5300:abcd:1234:5678:9abc
  app:
    image: nextcloud
    dns: 
      - 172.173.174.62
      - 2001:8a0:f2ff:5300:abcd:1234:5678:9abc
    ports:
      - 8181:80
    links:
      - db
    volumes:
      - /home/priminas5/dockerFiles/nextcloud/nextcloud:/var/www/html
    #restart: always

#sudo chown -R www-data:www-data nextcloud
