version: '2'
services:
  db:
    image: yobasystems/alpine-mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    #restart: always
    volumes:
      - /home/PI/dockerFiles/nextcloud/nextclouddb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    dns: 
      - <ipv4 dns>
      - <ipv6 dns>
  app:
    image: nextcloud
    dns: 
      - <ipv4 dns>
      - <ipv6 dns>
    ports:
      - 8181:80
    links:
      - db
    volumes:
      - /home/PI/dockerFiles/nextcloud/nextcloud:/var/www/html
    #restart: always

#sudo chown -R www-data:www-data nextcloud
