services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy

    environment:
      - <WG_TOKEN>
      - WG_HOST=PI.duckdns.org
      - PORT=12345
      - WG_PORT=12345
      - WG_DEFAULT_DNS=y.y.y.1
      - WG_DEFAULT_ADDRESS=y.y.y.x
      #- WG_DEFAULT_ADDRESS_V6=y:y::x
      - WG_DEVICE=eth0

    volumes:
      - /home/PI/dockerFiles/wg/config:/etc/wireguard
      - /lib/modules:/lib/modules
      #- /home/PI/dockerFiles/wg/lib/modules:/lib/modules
      #- /home/PI/dockerFiles/wg/etc/wireguard:/etc/wireguard
      #- /home/PI/dockerFiles/wg/home:/home

    network_mode: host
    #ports:
    #  - "44042:44042/udp"
    #  - "44041:44041/tcp"
      
    dns: 
      - <ipv4 dns>
      - <ipv6 dns>

    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    #sysctls:
    #  - net.ipv4.ip_forward=1
    #  - net.ipv4.conf.all.src_valid_mark=1

